(function () {
  "use strict";

  const LANG = {
    uz: {
      lang_name: "O'zbekcha",
      nav_home: "Bosh sahifa",
      nav_shop: "Do'kon",
      nav_earn: "Tanga yig'ish",
      nav_games: "O'yinlar",
      nav_leaderboard: "Reyting",
      nav_tasks: "Vazifalar",
      nav_bot: "Bot",
      nav_chat: "Chat",
      nav_admin: "Admin",
      topbar_profile: "Profil",
      topbar_coins: "Jami tangalar (joriy profil)",
      hero_eyebrow: "mini-platforma",
      hero_lead: "Tangalarni yig'ing, do'konda sarflang. Bir kompyuterni bir necha kishi ishlatsa, yuqoridagi <strong>Profil</strong> orqali har kishi uchun alohida balans yarating (akkaunt va server shart emas — ma'lumotlar brauzerda). O'yinlardagi «zxmax ga o'tkazish» joriy tanlangan profil balansiga tushadi.",
      hero_btn_earn: "Tanga olish",
      hero_btn_shop: "Do'kon",
      card_daily_title: "Kunlik bonus",
      card_daily_desc: "Har kuni bir marta bepul tanga.",
      card_daily_btn: "Bonusni olish",
      card_ach_title: "Yutuqlar",
      card_stats_title: "Statistika",
      card_stats_spent: "Jami ishlangan",
      card_stats_earned: "Jami yig'ilgan",
      card_stats_bought: "Sotib olingan",
      shop_title: "Do'kon",
      shop_desc: "Tangalar bilan kosmetika va imkoniyatlar.",
      earn_title: "Tanga yig'ish",
      earn_desc: "O'yinlar, bonuslar va vazifalar orqali tanga ishlang.",
      games_title: "O'yinlar",
      games_desc: "O'ynang va tanga yutib oling. Yutuqlar avtomatik profil balansiga tushadi.",
      leaderboard_title: "Reyting",
      leaderboard_desc: "Eng boy foydalanuvchilar.",
      tasks_title: "Vazifalar",
      tasks_desc: "Kunlik vazifalarni bajarib, qo'shimcha tanga oling.",
      bot_title: "Bot",
      bot_desc: "Telegram bot orqali tanga o'tkazish.",
      chat_title: "Chat",
      chat_desc: "Boshqa foydalanuvchilar bilan muloqot.",
      chat_public: "🌍 Umumiy",
      chat_friends: "👥 Do'stlar",
      chat_groups: "👥 Guruhlar",
      chat_requests: "📨 So'rovlar",
      login_title: "Kirish",
      login_btn: "Kirish",
      login_hint: "Email yoki username kiriting.",
      register_title: "Ro'yxatdan o'tish",
      register_btn: "Ro'yxatdan o'tish",
      register_hint: "Username kiriting.",
      login_lead: "Akkauntingizga kirish uchun username va parolni kiriting.",
      login_username_label: "Foydalanuvchi nomi",
      login_password_label: "Parol",
      login_register_btn: "Ro'yxatdan o'tish",
      login_send_email: "Email jo'natish",
      login_forgot_pass: "Parolni unutdim",
      register_lead: "Yangi akkaunt yaratish uchun ma'lumotlarni to'ldiring.",
      register_username_label: "Foydalanuvchi nomi",
      register_password_label: "Parol",
      register_name_label: "Ism (ixtiyoriy)",
      register_email_label: "Email (parolni tiklash uchun)",
      register_login_btn: "Kirish",
      logout_btn: "Chiqish",
      daily_claim: "Bonusni olish",
      daily_done: "Bugungi bonus olindi!",
      daily_streak: "Streak: {n} kun",
      daily_wait: "Kutish kerak: {time}",
      quick_earn: "Tez topish",
      quick_earn_cooldown: "Kutish: {s}s",
      shop_buy: "Sotib olish",
      shop_bought: "Sotib olingan",
      shop_vip: "VIP nishoni",
      shop_rainbow: "Kamalak nom",
      shop_dark: "Qora fon",
      shop_coinboost: "Tanga kuchaytirish",
      shop_magnet: "Tanga magniti",
      shop_xpboost: "XP kuchaytirish",
      shop_streakfreeze: "Streyk muzlatish",
      shop_anonym: "Anonim",
      shop_chatcolor: "Chat rangi",
      task_daily: "Kunlik bonusni oling",
      task_play: "O'yin o'ynang",
      task_earn: "Tanga ishlang",
      task_shop: "Do'kondan xarid qiling",
      task_streak: "Streyni saqlang",
      transfer_title: "zxmax ga o'tkazish",
      transfer_btn: "O'tkazish",
      lang_select: "Tilni tanlang",
      galaxy_settings: "Sozlamalar",
      galaxy_music: "Musiqa",
      galaxy_sound: "Ovoz",
      galaxy_lang: "Til",
      lb_title: "Reyting",
      lb_desc: "Eng ko'p tanga yig'gan foydalanuvchilar.",
      lb_all: "Hamma",
      lb_weekly: "Haftalik",
      lb_monthly: "Oylik",
      admin_title: "Admin panel",
      admin_desc: "Foydalanuvchilarni boshqarish.",
      footer_note: "profillar va tangalar brauzerda (localStorage); boshqa qurilmada ko'rinmaydi",
      gt_title: "Galaxy Tycoon: Ultra Edition",
      gt_balance: "Pul: {0} 💰",
      gt_income: "Keladigon foyda: {0} 💰 / 2s",
      gt_settings: "Sozlamalar",
      gt_music: "Musiqa ovoz:",
      gt_sfx: "Effektlar ovoz:",
      gt_lang: "Til:",
      gt_lang_btn: "Tilni o'zgartirish",
      gt_back: "Orqaga",
      page_title: "zxmax — tangalar va do'kon",
      nav_aria: "Asosiy",
      hamburger_label: "Menyu",
      quick_earn_title: "Tez tanga",
      quick_earn_desc: "Qisqa tanaffus: kichik miqdor, lekin tez.",
      quick_earn_btn: "+ tanga",
      earn_next_title: "Keyingi qadam: o'yinlar",
      earn_next_desc: "Alohida HTML fayllar sifatida o'yin qo'shishingiz mumkin — ularni <code>games/</code> papkasiga qo'ying va <a href=\"#games\">{0}</a> bo'limida havola qiling.",
      earn_next_link: "O'yinlar",
      chat_night_msg: "🌙 Umumiy chat tungi soat 00:00 dan 06:00 gacha yopiq",
      chat_input_placeholder: "Xabar yozish...",
      chat_private_placeholder: "Shaxsiy xabar...",
      chat_group_placeholder: "Guruh nomi...",
      chat_group_input_placeholder: "Guruhga xabar...",
      chat_send_btn: "Yuborish",
      chat_create_group: "+ Guruh",
      login_username_placeholder: "Username",
      login_password_placeholder: "Parol",
      register_name_placeholder: "Ism yoki taxallus",
      register_email_placeholder: "email@example.com",
      task_play_one: "Bitta o'yin o'yna",
      task_play_three: "3 ta o'yin o'yna",
      task_earn_50: "50◎ tanga ishlang",
      task_earn_200: "200◎ tanga ishlang",
      task_shop_30: "Do'konda 30◎ sarflang",
      task_shop_100: "Do'konda 100◎ sarflang",
      task_subscribe: "Kimdirga obuna bo'l",
      task_daily_bonus: "Kunlik bonusni ol",
      task_quick_earn: "Tez tanga ishlat",
      task_claim_btn: "Olish",
      task_completed: "Bajarildi",
      task_reward_toast: "+{0} tanga (vazifa)",
      bot_login_first: "Avval profilingizga kiring.",
      bot_balance: "💳 Firebase balansingiz: {0} ◎",
      bot_instruction: "Tangalaringizni Telegram botga yuboring. Bot: @zxmaxcoinbot. Miqdorni kiriting va \"Yuborish\" tugmasini bosing.",
      bot_amount_placeholder: "Miqdor",
      bot_send_btn: "Yuborish",
      bot_claim_instruction: "Telegramda /claim yozing",
      bot_check_btn: "🔄 Tekshirish",
      bot_amount_error: "❌ Miqdorni kiriting!",
      bot_balance_error: "❌ Balansingiz yetarli emas!",
      bot_success: "✅ {0}◎ yuborildi! Telegram botda /claim yozing.",
      bot_error_prefix: "❌ Xatolik: ",
      bot_pending: "📌 {0}◎ kutilmoqda. /claim yozing.",
      bot_nothing: "Hech narsa yo'q.",
    },
  };

  window.__ = function (key, ...args) {
    let text = LANG.uz[key] || key;
    if (args.length) {
      args.forEach((v, i) => { text = text.replace(`{${i}}`, v); });
    }
    return text;
  };

  window.__lang = function () { return "uz"; };
  window.__setLang = function () {};
  window.__langs = function () { return ["uz"]; };
  window.__langName = function () { return "O'zbekcha"; };

  document.documentElement.lang = "uz";
})();
